# ╔════════════════════════════════════════════════════════════════════════════════╗
# ║                                                                                ║
# ║           ████                                ███  █████   █████               ║
# ║          ░░███                               ░░░  ░░███   ░░███                ║
# ║    ██████ ░███   ██████    ██████  ████████  ████ ███████ ███████  █████ ████  ║
# ║   ░░░░░███░███  ░░░░░███  ███░░███░░███░░███░░███░░░███░ ░░░███░  ░░███ ░███   ║
# ║    ███████░███   ███████ ░███ ░░░  ░███ ░░░  ░███  ░███    ░███    ░███ ░███   ║
# ║   ███░░███░███  ███░░███ ░███  ███ ░███      ░███  ░███ ███░███ ███░███ ░███   ║
# ║  ░░████████████░░████████░░██████  █████     █████ ░░█████ ░░█████ ░░███████   ║
# ║   ░░░░░░░░░░░░  ░░░░░░░░  ░░░░░░  ░░░░░     ░░░░░   ░░░░░   ░░░░░   ░░░░░███   ║
# ║                                                                     ███ ░███   ║
# ║                                                                    ░░██████    ║
# ║                                                                     ░░░░░░     ║
# ║                                                                                ║
# ╚════════════════════════════════════════════════════════════════════════════════╝

[general]
import = [
	"~/.config/alacritty/theme.toml",
]

[font]
size = 14.0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[window]
opacity = 1.0
padding = { x = 3, y = 3 }
dynamic_padding = true
dimensions = { columns = 80, lines = 27 }
