# ╔═══════════════════════════════════════════════════════╗
# ║                                                       ║
# ║   █████                █████                          ║
# ║  ░░███                ░░███                           ║
# ║   ░███ █████  ██████   ░███ █████ ████████   ██████   ║
# ║   ░███░░███  ░░░░░███  ░███░░███ ░░███░░███ ███░░███  ║
# ║   ░██████░    ███████  ░██████░   ░███ ░░░ ░███ ░░░   ║
# ║   ░███░░███  ███░░███  ░███░░███  ░███     ░███  ███  ║
# ║   ████ █████░░████████ ████ █████ █████    ░░██████   ║
# ║  ░░░░ ░░░░░  ░░░░░░░░ ░░░░ ░░░░░ ░░░░░      ░░░░░░    ║
# ║                                                       ║
# ╚═══════════════════════════════════════════════════════╝

##################
# GENERAL TWEAKS #
##################

# disable clippy ascii art
set global ui_options terminal_assistant=none

# set info window
set -add global autoinfo normal

# line numbers
addhl global/ number-lines -hlcursor

# highlight matching
addhl global/ show-matching
set-face global MatchingChar white,black+b

# tabs as 4 chars
set-option global tabstop 4

# enable "soft" line wrap
addhl global/ wrap

# enable git support
hook global WinCreate .* %{
    git show-diff
}


hook global BufWritePost .* %{
    git update-diff
}

# autocomplete using tab key
hook global InsertCompletionShow .* %{ map window insert <tab> <c-n> }
hook global InsertCompletionShow .* %{ map window insert <s-tab> <c-p> }
hook global InsertCompletionHide .* %{ unmap window insert <tab> <c-n> }
hook global InsertCompletionHide .* %{ unmap window insert <s-tab> <c-p> }

# always remove trailing whitespace
hook global BufWritePre .* %{ try %{ execute-keys -draft \%s\h+$<ret>d } }

# highlight special comments
add-highlighter global/ regex \b(TODO|FIXME|XXX|NOTE)\b 0:default+rb

#######################
# FILE-TYPE DEPENDENT #
#######################

# create shellscripting environment
hook global BufCreate APKBUILD %{
    set-option buffer filetype sh
}
hook global BufSetOption filetype=sh %{
    set buffer formatcmd 'shfmt'
    set buffer lintcmd 'shellcheck -f gcc'
    hook buffer BufWritePost .* %{ lint }
    hook buffer InsertEnd .* %{ lint }
    hook buffer NormalIdle .* %{ lint }
}

# create python development environment
hook global BufSetOption filetype=python %{
    set buffer formatcmd 'autopep8 - '
    #set buffer lintcmd 'flake8 --ignore=W191 --format="%(path)s:%(row)d:%(col)d: error: %(text)s"'
    #hook buffer BufWritePost .* %{ lint }
    #hook buffer InsertEnd .* %{ lint }
    #hook buffer NormalIdle .* %{ lint }
}
hook global WinSetOption filetype=python %{
    jedi-enable-autocomplete
}

# create c development environment
hook global BufSetOption filetype=c %{
    set buffer formatcmd 'indent -linux -i4 -ts4'
    clang-enable-autocomplete
    clang-enable-diagnostics
    set buffer clang_options '-std=c11 -Wall -Wextra -pedantic'
    alias buffer lint clang-parse
    alias buffer lint-next clang-diagnostics-next
    hook buffer BufWritePost .* %{ lint }
    hook buffer InsertEnd .* %{ lint }
    hook buffer NormalIdle .* %{ lint }
}

# set up markdown environment
hook global BufSetOption filetype=markdown %{
    # set word wrap
    add-highlighter buffer/wordwrap wrap -word
}

# set up html environment
hook global BufSetOption filetype=html %{
    set buffer formatcmd "run(){tidy -q -omit -w 80 -utf8 2>/dev/null || true; } && run"
    set buffer lintcmd "tidy -e -omit --gnu-emacs yes --quiet yes 2>&1"
    set buffer tabstop 2
	set buffer disabled_hooks .*-indent
    hook buffer BufWritePost .* %{ lint }
    hook buffer InsertEnd .* %{ lint }
    hook buffer NormalIdle .* %{ lint }
}

# set up js environment
#hook global BufSetOption filetype=javascript %{
#}

# set up verilog development environment
hook global BufSetOption filetype=verilog %{
    # see the file in my ~/bin
    set buffer lintcmd 'verilog_lint'
    lint
    hook buffer BufWritePost .* %{ lint }
    hook buffer InsertEnd .* %{ lint }
    hook buffer NormalIdle .* %{ lint }
}

# set up systemverilog development environment
hook global BufSetOption filetype=systemverilog %{
    set buffer lintcmd 'verible-verilog-lint'
    lint
    hook buffer BufWritePost .* %{ lint }
    hook buffer InsertEnd .* %{ lint }
    hook buffer NormalIdle .* %{ lint }
}

# set up latex environment
hook global BufCreate .*\.tex %{
    set-option buffer filetype latex
}
hook global BufCreate .*\.latex %{
    set-option buffer filetype latex
}
hook global BufSetOption filetype=latex %{
    # don't wrap words around
    add-highlighter window/wordwrap wrap -word

    #set-option buffer makecmd 'latexmk -pdf -quiet'
    set-option buffer makecmd 'pdflatex'
    set-option buffer lintcmd 'chklatex %f:%l:%c: %k: %n %m'
    set-option buffer formatcmd 'latexindent'

    hook bugger BufWritePost .* %{
#        lint
        make
    }
}

# set up go environment
hook global BufSetOption filetype=go %{
    set-option buffer formatcmd 'gofmt'
    set-option buffer makecmd 'go build'
    hook buffer BufWritePost .* %{ format }
    #hook buffer InsertEnd .* %{ lint }
    #hook buffer NormalIdle .* %{ lint }
}

###########
# PLUGINS #
###########

# use kak-bundle
evaluate-commands %sh{
  # We're assuming the default bundle_path here...
  plugins="$kak_config/bundle"
  mkdir -p "$plugins"
  [ ! -e "$plugins/kak-bundle" ] && \
    git clone -q https://codeberg.org/jdugan6240/kak-bundle "$plugins/kak-bundle"
  printf "%s\n" "source '$plugins/kak-bundle/rc/kak-bundle.kak'"
}
bundle-noload kak-bundle https://codeberg.org/jdugan6240/kak-bundle

bundle kakoune-expand "https://github.com/occivink/kakoune-expand"

bundle kakoune-mirror "https://github.com/delapouite/kakoune-mirror" %{
    # Suggested mapping: use ' to get into mirror mode
    map global normal "'" ': enter-user-mode -lock mirror<ret>'
}

# clipboard integration
bundle kakboard "https://github.com/lePerdu/kakboard" %{
    hook global WinCreate .* %{ kakboard-enable }
}

bundle-theme selenized "https://github.com/TeddyDD/kakoune-selenized"

bundle-theme second-light  "https://github.com/vbauerster/second-light"

bundle-theme base16 "https://github.com/AprilArcus/base16-kakoune"
# setup color
colorscheme plain

bundle smarttab.kak "https://github.com/andreyorst/smarttab.kak" %{
    hook global WinSetOption filetype=(c|verilog|sh) noexpandtab
    hook global WinSetOption filetype=(python|java|html) expandtab
}

#bundle "https://github.com/kak-lsp/kak-lsp" do %{
#    cargo install --locked --force --path .
#} # Installed via distribution package management
eval %sh{kak-lsp --kakoune -s $kak_session}  # Not needed if you load it with kak-bundle
hook global WinSetOption filetype=(python|go|latex|c|cpp) %{
    lsp-enable-window
    lsp-auto-hover-enable
    # format buffer on write
    #hook window BufWritePre .* lsp-formatting-sync
    set global lsp_diagnostic_line_error_sign '║'
    set global lsp_diagnostic_line_warning_sign '┊'
    set global lsp_auto_highlight_references true
}

bundle kakoune-rainbow "https://github.com/jjk96/kakoune-rainbow"

bundle kakoune-verilog "https://github.com/tmahlburg/kakoune-verilog"
bundle kakoune-systemverilog "https://github.com/tmahlburg/kakoune-systemverilog"

bundle active-window.kak "https://github.com/greenfork/active-window.kak"

# called via woc
bundle wordcount.kak "https://github.com/ftonneau/wordcount.kak"

bundle insert-indicator "https://github.com/casonadams/insert-indicator"
bundle kak-ansi "https://github.com/eraserhd/kak-ansi"
